apiVersion: v1
kind: Pod
metadata:
  name: brahma2pods
spec:
  containers:
    - name: nginx-bgg
      image: nginx
      ports:
        - containerPort: 8080
    - name: watcher-bgg
      image: bgannur/aws-training
      ports:
        - containerPort: 8090
